services:
  app:
    build: .
    container_name: ${CONTAINER_NAME}
    ports:
      - '${PORT}:3000'  # Usar la variable de entorno PORT
    depends_on:
      - db
    env_file:
      - .env  # Cargar las variables de entorno desde el archivo .env
    volumes:
      - .:/app
      - /app/node_modules

  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}  # Usar la variable de entorno DB_PASSWORD
      MYSQL_DATABASE: ${DB_NAME}           # Usar la variable de entorno DB_NAME
    ports:
      - '3307:3306'  # Usar la variable de entorno PORT_DB
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: